image: node:22-alpine

stages:
  - install
  - test
  - build
  - release

variables:
  NODE_OPTIONS: '--max-old-space-size=4096' # 4GB RAM limit

cache:
  key: ${CI_COMMIT_REF_SLUG}
  policy: pull
  paths: [.npm]

install:
  stage: install
  script:
    - npm ci --prefer-offline --cache .npm --no-audit --progress=false
  artifacts:
    paths: [node_modules]
    expire_in: 1 day
  cache:
    policy: pull-push

test_unit:
  stage: test
  script:
    - npm run test
  coverage: /All files[^|]*|[^|]*\s+([\d\.]+)/
  artifacts:
    paths: [coverage]
    expire_in: 1 day
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml
      junit:
        - junit.xml

test_lint:
  stage: test
  script:
    - npm run lint

test_format:
  stage: test
  script:
    - npm run format:check

test_typecheck:
  stage: test
  script:
    - npm run typecheck

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths: [build]
    expire_in: 1 day

audit:
  stage: test
  script:
    - npm run audit
  allow_failure: true

release:
  stage: release
  image: node:22-alpine
  before_script:
    - apk add --no-cache git
    - npm ci --prefer-offline --cache .npm --no-audit --progress=false
  script:
    - npx semantic-release
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  only:
    - main
