# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1
# Builder stage
FROM node:lts-alpine AS builder
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json tsconfig.json ./
COPY src ./src
RUN npm ci --ignore-scripts

# Build
RUN npm run build

# Runtime stage
FROM node:lts-alpine AS runner
WORKDIR /app

# Copy built files and production deps
COPY --from=builder /app/build ./build
COPY package.json package-lock.json ./

# Install production dependencies without running scripts
RUN npm ci --omit=dev --ignore-scripts

# Default command
CMD ["node", "build/index.js"]
